## Importing the libraries

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset



In [ ]:
dataset = pd.read_csv('cars_dataset.csv')
x = dataset.iloc[:,:-1].values
y = dataset.iloc[:,-1].values

### printing the x and y variables

In [ ]:
print(x)

[['Ford' 3.0 2.0 55000]
 ['Volkswagen' 1.0 1.6 67000]
 ['BMW' 4.0 3.0 120000]
 ['Ford' 6.0 nan 35000]
 ['BMW' 5.0 2.5 95000]
 ['Volkswagen' 2.0 1.4 52000]
 ['Ford' nan 1.8 40000]
 ['BMW' 3.0 3.2 115000]
 ['Volkswagen' 7.0 1.6 30000]
 ['Ford' 4.0 2.0 58000]]


In [ ]:
print(y)

['Yes' 'No' 'Yes' 'No' 'No' 'No' 'Yes' 'Yes' 'No' 'No']


## Replacing empty values by the mean

In [ ]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan,strategy='mean')
imputer.fit(x[:,1:3])
x[:,1:3]=imputer.transform(x[:,1:3])

## Encoding categorical data in x variable

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [ ]:
print(x)

[[0.0 1.0 0.0 3.0 2.0 55000]
 [0.0 0.0 1.0 1.0 1.6 67000]
 [1.0 0.0 0.0 4.0 3.0 120000]
 [0.0 1.0 0.0 6.0 2.1222222222222222 35000]
 [1.0 0.0 0.0 5.0 2.5 95000]
 [0.0 0.0 1.0 2.0 1.4 52000]
 [0.0 1.0 0.0 3.888888888888889 1.8 40000]
 [1.0 0.0 0.0 3.0 3.2 115000]
 [0.0 0.0 1.0 7.0 1.6 30000]
 [0.0 1.0 0.0 4.0 2.0 58000]]


## Label encoding categorical data in y variable

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [ ]:
print(y)

[1 0 1 0 0 0 1 1 0 0]


## Splitting dataset into training and test set

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 1)

In [ ]:
print(x_train)

[[0.0 1.0 0.0 3.888888888888889 1.8 40000]
 [1.0 0.0 0.0 5.0 2.5 95000]
 [0.0 1.0 0.0 3.0 2.0 55000]
 [0.0 1.0 0.0 6.0 2.1222222222222222 35000]
 [0.0 0.0 1.0 1.0 1.6 67000]
 [1.0 0.0 0.0 3.0 3.2 115000]
 [0.0 0.0 1.0 7.0 1.6 30000]
 [0.0 0.0 1.0 2.0 1.4 52000]]


## Applying feature scaling


In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

## Build linear regression

### Importing library

In [ ]:
from sklearn import linear_model
from sklearn.metrics import mean_squared_error, r2_score

### Defining regression model

In [ ]:
model = linear_model.LinearRegression()

### Build training model

In [ ]:
model.fit(x_train,y_train)

LinearRegression()

### Apply trained model to make prediction

In [ ]:
y_pred = model.predict(x_test)

### Prediction results

In [ ]:
print('Coefficients ', model.coef_)
print('Intercept ', model.intercept_)
print('Mean squared error (MSE): %.2f'
      % mean_squared_error(y_test, y_pred))
print('Coefficient of determination (R^2): %.2f'
      % r2_score(y_test, y_pred))

Coefficients  [ 0.11362857  0.03328023 -0.13491272 -0.40151625  0.49668939 -0.55266837]
Intercept  0.37499999999999983
Mean squared error (MSE): 0.33
Coefficient of determination (R^2): -0.30
